### ISSUE TITLE
Hide API token

### ISSUE THREAD

**Issue by larskarbo** [CyrielleAlbert/one_weekend_one_project#1]
https://github.com/CyrielleAlbert/one_weekend_one_project/blob/8625450040eba037d3722a46ea350aac215561e7/1_telegram_newsletter/main.py#L76

You should move the token to an environment variable.

**Comment by larskarbo** [comment]
hey, you can't just close this without fixing it?

**Comment by CyrielleAlbert** [comment]
Nop I fixed it but I didn't used the environment variable but I used a file which contains the tokens/keys.

**Comment by larskarbo** [comment]
ok I am laying flat
